Updated the lookup to enable the referenceEntityRecord type
php-etl/akeneo-plugin pull request #23
Opened 2022-05-02 12:46 UTC by sebprt

2022-05-03 20:50 UTC, gplanchat requested changes

2022-05-03 20:50 UTC, gplanchat commented on src/Builder/Capacity/Lookup/Get.php
>                          ],
Il faut laisser les arguments nommés

2022-05-06 10:06 UTC, sebprt commented on src/Builder/Capacity/Lookup/Get.php
>                          ],
J'ai changé ma façon de faire, en laissant les arguments nommés

2022-05-16 09:17 UTC, gplanchat commented on src/Configuration/Extractor.php
> +                ->thenInvalid('The code option should only be used with the "attributeOption", and "assetManager" endpoints.')
```suggestion
                ->thenInvalid('The code option should only be used with the "attributeOption" and "assetManager" endpoints.')
```

2022-05-16 09:19 UTC, gplanchat approved these changes

2022-05-16 09:21 UTC, merged