Added a missing type on a variable
php-etl/akeneo-plugin pull request #4
Opened 2021-05-20 15:23 UTC by sebprt

2021-05-21 07:14 UTC, clemzarch approved these changes

2021-05-21 15:17 UTC, sebprt commented on examples/config.yaml
> +        method: listPerPage
**code** peut aussi être une expression language

2021-05-26 09:18 UTC, clemzarch commented on src/Builder/ConditionalLookup.php
> +                            return $parser->parse('<?php ' . $this->interpreter->compile($condition, ['input']) . ';')[0]->expr;
ca peut etre remplacé par `return new Node\Scalar\String_($this->code),` comme dans `Builder/Capacity/Extractor/All.php` ligne 85 ?

2021-05-27 08:33 UTC, gplanchat requested changes

2021-05-27 08:33 UTC, gplanchat commented on src/Capacity/Extractor/ListPerPage.php
> +    private function compileValue(null|bool|string|int|float|array|Expression $value): Node\Expr
Cette méthode devrait être refactorisée et déplacée dans `php-etl/satellite-toolbox`, ça serait bien utile de pouvoir le retrouver dans différents packages

2021-05-27 08:33 UTC, gplanchat commented on src/Capacity/Lookup/All.php
> +use function Webmozart\Assert\Tests\StaticAnalysis\null;
Attention, tu as chargé une fonction nommée `null()`

2021-05-27 08:33 UTC, gplanchat commented on src/Configuration/Extractor.php
>                  ->scalarNode('method')->isRequired()->end()
Est-ce que tu peux également ajouter `method` en tant qu'option qui peut utiliser ExpressionLanguage ?

2021-05-27 08:33 UTC, gplanchat commented on src/Factory/Lookup.php
> +
Tu as la fonction `compileValueWhenExpression()` dans `php-etl/satellite-toolbox` qui te permet de faire ça

2021-05-27 13:49 UTC, sebprt commented on src/Capacity/Lookup/All.php
> +use function Webmozart\Assert\Tests\StaticAnalysis\null;
Supprimé

2021-05-27 13:50 UTC, sebprt commented on src/Factory/Lookup.php
> +
Modifié

2021-05-28 07:59 UTC, merged