Improved the upsertList management for the attributeOption endpoint
php-etl/akeneo-plugin pull request #51
Opened 2023-06-28 13:36 UTC by sebprt

2023-07-04 07:06 UTC, clemzarch commented on src/Configuration/Loader.php
> +                ->scalarNode('attributeCode')
faut mettre à jour la doc ?

2023-07-04 07:18 UTC, clemzarch approved these changes

2023-07-05 08:45 UTC, gplanchat requested changes

2023-07-05 08:45 UTC, gplanchat commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => \array_key_exists('referenceEntityAttributeOption', $data)
**🔨 issue:** Les champs des fichiers de configuration sont tous en `snake_case` de partout

2023-07-05 08:45 UTC, gplanchat commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => \array_key_exists('attributeCode', $data)
**🔨 issue:** Les champs des fichiers de configuration sont tous en `snake_case` de partout

2023-07-05 08:45 UTC, gplanchat commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => !\array_key_exists('attributeCode', $data)
**🔨 issue:** Les champs des fichiers de configuration sont tous en `snake_case` de partout

2023-07-05 10:04 UTC, sebprt commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => \array_key_exists('referenceEntityAttributeOption', $data)
C'est fait

2023-07-05 10:04 UTC, sebprt commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => \array_key_exists('attributeCode', $data)
C'est fait

2023-07-05 10:04 UTC, sebprt commented on src/Configuration/Loader.php
> +                ->ifTrue(fn ($data) => !\array_key_exists('attributeCode', $data)
C'est fait

2023-07-05 10:31 UTC, gplanchat approved these changes

2023-07-05 10:31 UTC, merged