Add new parameter for endpoint category
php-etl/akeneo-plugin pull request #60
Opened 2024-05-23 14:14 UTC by JoMessina

Add with_enriched_attributes parameter to pull template's attributes on enriched categories

2024-05-24 14:59 UTC, sebprt requested changes

2024-05-24 14:59 UTC, sebprt commented on src/Configuration/Extractor.php
> +                ->end()
J'aurai plutôt utilisé un `booleanNode` avec comme valeur pas défaut `false`

https://symfony.com/doc/current/components/config/definition.html#variable-nodes

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/ListPerPage.php
> +    private ?Node\Expr $code = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/Get.php
> +    private ?string $type = '';
Tu as 2 écritures différentes pour le nullable. Mets des  `?` partout plutôt que `|null`.

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/Get.php
> +    }
Le constructeur ne sert à rien

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/ListPerPage.php
> +    }
Le constructeur ne sert à rien, tu peux le supprimer

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/Download.php
> +    private ?Node\Expr $file = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/All.php
> +    private ?Node\Expr $code = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Lookup/All.php
> +    }
Le constructeur ne sert à rien, tu peux le supprimer

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Loader/UpsertList.php
> +    private ?Node\Expr $attributeCode = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Loader/Upsert.php
> +    private ?Node\Expr $referenceEntityAttribute = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Extractor/ListPerPage.php
> +    private ?Node\Expr $code = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Extractor/ListPerPage.php
> +    }
Le constructeur ne sert à rien, tu peux le supprimer

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Extractor/Get.php
> +    private ?Node\Expr $identifier = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Extractor/Get.php
> +    }
Le constructeur ne sert à rien, tu peux le supprimer

2024-05-24 14:59 UTC, sebprt commented on src/Builder/Capacity/Extractor/All.php
> +    private ?Node\Expr $withEnrichedAttributes = null;
Tu as 2 écritures différentes pour le nullable. Mets des `?` partout plutôt que `|null`

2024-05-27 07:46 UTC, JoMessina commented on src/Builder/Capacity/Lookup/ListPerPage.php
> +    private ?Node\Expr $code = null;
Impossible d'utiliser le ```?``` avec les ```|```, je laisse en l'état plutôt que de mettre des ```|null``` partout.

2024-05-27 07:46 UTC, JoMessina commented on src/Builder/Capacity/Lookup/Get.php
> +    private ?string $type = '';
Impossible d'utiliser le ```?``` avec les ```|```, je laisse en l'état plutôt que de mettre des ```|null``` partout.

2024-05-27 07:46 UTC, JoMessina commented on src/Builder/Capacity/Extractor/ListPerPage.php
> +    private ?Node\Expr $code = null;
Impossible d'utiliser le ```?``` avec les ```|```, je laisse en l'état plutôt que de mettre des ```|null``` partout.

2024-05-27 07:46 UTC, JoMessina commented on src/Builder/Capacity/Extractor/Get.php
> +    private ?Node\Expr $identifier = null;
Impossible d'utiliser le ```?``` avec les ```|```, je laisse en l'état plutôt que de mettre des ```|null``` partout.

2024-05-27 07:46 UTC, JoMessina commented on src/Builder/Capacity/Extractor/All.php
> +    private ?Node\Expr $withEnrichedAttributes = null;
Impossible d'utiliser le ```?``` avec les ```|```, je laisse en l'état plutôt que de mettre des ```|null``` partout.

2024-05-27 08:40 UTC, JoMessina commented on src/Configuration/Extractor.php
> +                ->end()
J'ai retiré la valeur par défaut car celà ajoute le paramètre à toutes les configuration, hors il s'agit ici d'un paramètre réservé à l'endpoint category

2024-05-28 14:39 UTC, merged